### ISSUE TITLE
Feature Suggestion: custom breakpoint condition

### ISSUE THREAD

**Issue by cvigano** [NamelessCoder/typo3-cms-fluid-debug#2]
This extension is really great and helping a lot. What I'm missing from working with PhpStorm's system of breakpoint condition is the ability to define a condition upon which the breakpoint triggers.

Now, my idea is that we can optionally pass a condition function as an argument to `f:debug` which get's called when set to which the context of `DebugViewHelper::breakPoint` is passed, so that in theory the condition function is able to check on all the variables that are available in `DebugViewHelper::breakPoint`.

Is a feature like that even possible? I'm not even sure. But I think it would help a lot :grinning:.

**Comment by NamelessCoder** [comment]
Already supported ;)

```xml
<f:debug.break break="{myVar} == 1" />
```

...and Bob's your uncle. Since `break` is a boolean argument it supports conditions. The "problem" if you can call it that, is that the default value of `break` is `false` for `f:debug` but `true` for `f:debug.break` - but you can still write boolean expressions, including nested and whatever syntax `f:if` supports.

**Comment by cvigano** [comment]
While this is a cool feature and something I haven't thought of, it does not solve the original problem, which is "Is there a way to trigger the breakpoint on some internal state of the Fluid Rendering Engine?". I'm sorry, I didn't phrase that in an exact way. :slightly_frowning_face:

**Comment by NamelessCoder** [comment]
If by internal state you mean things like what is in the ViewHelperVariableContainer or RenderingContext, but not accessible in the template layer itself, then I'm afraid there's no easy way to do that from the template layer. The best choice then would be to set your break point in either of the override classes and have your IDE set the breakpoints. Then you would only need to find that class and set `break="0"` on `f:debug.break` to disable the automatic breaking in favour of your own, conditional breaks. IMHO it is fine to have to put breakpoints in third-party code; since you wouldn't have to edit it to get it done.

Note though that it may make more sense to debug in the TemplateParser, TemplateCompiler, ViewHelperResolver or other if your need for detail and precision is high. When you debug via the template you are debugging on a separated state; you have limited access to the state of the TemplateParser for example.

Hope I'm not missing anything... my logic is that breakpoint control is only necessary if you already use xdebug + IDE and if you do, breakpoints can be easily set anywhere in framework or vendor code without needing to configure your runtime to call a certain method.

**Comment by cvigano** [comment]
Okay, now I get it. Sorry for the noise, I tend to overengineer if I'm excited about a new piece of software but your explanation makes a lot of sense. Thank you. :)

**Comment by NamelessCoder** [comment]
You're welcome :)
